// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || 'https://qliinxtanjdnwxlvnxji.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!import.meta.env.VITE_SUPABASE_URL) {
  console.warn('⚠️ VITE_SUPABASE_URL is missing in .env. Using fallback URL:', SUPABASE_URL);
}

if (!import.meta.env.VITE_SUPABASE_ANON_KEY) {
  console.error('🚨 VITE_SUPABASE_ANON_KEY is missing in .env! Authentication will fail.');
} else {
  // VITE_SUPABASE_ANON_KEY is set
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // PKCE: le SDK doit lire le ?code= dans l'URL pour établir la session
    storageKey: 'supabase.auth.token',
    flowType: 'pkce',
  },
  global: {
    headers: {
      Accept: 'application/json',
    },
  },
});

// Gérer les erreurs de refresh token globalement
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    // Token refreshed successfully — no action needed
  }

  if (event === 'SIGNED_OUT') {
    // Nettoyer complètement le localStorage en cas de déconnexion
    localStorage.removeItem('lastActivity');
    localStorage.removeItem('manualLogout');
  }
});
